//! The one place the shop reads and writes files.
//!
//! Every caller goes through here, which is what makes remote object storage a
//! second implementation later rather than a search through the code
//! (`docs/adr/0004-v1-release-scope.md`).
//!
//! Nothing a client sends ever becomes part of a path. A path is built from an
//! [`ImageReference`], which is either generated by the shop or parsed under a
//! rule that admits thirty-two hexadecimal characters and nothing else, and
//! from a file name chosen out of a closed set. A traversal has nowhere to
//! enter.

use std::io;
use std::path::{Path, PathBuf};

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;

/// Bytes of randomness behind a reference. A reference is public — it appears
/// in every image URL — so guessing one must be out of reach.
const REFERENCE_BYTES: usize = 16;
const REFERENCE_LENGTH: usize = REFERENCE_BYTES * 2;

/// Names the directory one image's files live in.
///
/// Hexadecimal rather than something shorter: it is never typed, it is
/// unambiguous on a case-insensitive filesystem, and the rule that validates
/// one arriving from outside is a single character class.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageReference(String);

impl ImageReference {
    pub fn generate() -> Self {
        let mut bytes = [0u8; REFERENCE_BYTES];
        getrandom::fill(&mut bytes).expect("the operating system provides randomness");

        let mut reference = String::with_capacity(REFERENCE_LENGTH);
        for byte in bytes {
            use std::fmt::Write;
            let _ = write!(reference, "{byte:02x}");
        }

        Self(reference)
    }

    /// Reads a reference from a URL. `None` for anything that is not exactly
    /// what [`generate`](Self::generate) produces — `..` and `/` among them,
    /// but the rule is what is allowed, never what is forbidden.
    pub fn parse(raw: &str) -> Option<Self> {
        let valid = raw.len() == REFERENCE_LENGTH
            && raw
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte));

        valid.then(|| Self(raw.to_owned()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// A size the shop serves (`docs/design/catalog.md` § 5). The number is the
/// long side, so a portrait and a landscape photograph sit in the same grid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Size {
    Thumbnail,
    Medium,
    Large,
}

impl Size {
    pub const ALL: [Self; 3] = [Self::Thumbnail, Self::Medium, Self::Large];

    pub fn long_side(self) -> u32 {
        match self {
            Self::Thumbnail => 200,
            Self::Medium => 600,
            Self::Large => 1400,
        }
    }

    fn as_str(self) -> &'static str {
        match self {
            Self::Thumbnail => "200",
            Self::Medium => "600",
            Self::Large => "1400",
        }
    }

    /// Reads a size from a URL. Named `parse` rather than `from_str`: the
    /// standard trait of that name returns a `Result`, and a method that looks
    /// like it but is not is worse than one that reads differently.
    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|size| size.as_str() == value)
    }
}

/// What a stored file is encoded as.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    /// What the shop serves. Five times smaller than the same picture in JPEG
    /// (`docs/backend/adr/0008-image-pipeline.md`).
    Avif,
    /// The fallback, and the only format the shop accepts on the way in.
    Jpeg,
}

impl Format {
    pub const ALL: [Self; 2] = [Self::Avif, Self::Jpeg];

    fn extension(self) -> &'static str {
        match self {
            Self::Avif => "avif",
            Self::Jpeg => "jpg",
        }
    }

    pub fn media_type(self) -> &'static str {
        match self {
            Self::Avif => "image/avif",
            Self::Jpeg => "image/jpeg",
        }
    }

    pub fn from_extension(value: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|format| format.extension() == value)
    }
}

/// One file of one image. A closed set: there is no way to name a file the
/// shop did not decide to keep.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Stored {
    /// The ≤ 2400 px JPEG the browser sent, kept so a size added later can be
    /// derived without asking the merchant for the file again. Never given its
    /// own URL; the shop substitutes it while a derived size is missing.
    Source,
    Derived(Size, Format),
}

impl Stored {
    fn file_name(self) -> String {
        match self {
            Self::Source => "source.jpg".to_owned(),
            Self::Derived(size, format) => format!("{}.{}", size.as_str(), format.extension()),
        }
    }
}

/// Where files live. Cloned per request, so it holds a path, never a handle.
#[derive(Debug, Clone)]
pub struct Storage {
    root: PathBuf,
}

impl Storage {
    pub fn at(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    fn directory(&self, reference: &ImageReference) -> PathBuf {
        self.root.join("images").join(reference.as_str())
    }

    fn path(&self, reference: &ImageReference, stored: Stored) -> PathBuf {
        self.directory(reference).join(stored.file_name())
    }

    /// Writes one file, creating the image's directory if this is its first.
    pub async fn write(
        &self,
        reference: &ImageReference,
        stored: Stored,
        bytes: Vec<u8>,
    ) -> io::Result<()> {
        let path = self.path(reference, stored);
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }
        tokio::fs::write(path, bytes).await
    }

    /// The file's bytes, or `None` when it is not there — which is the normal
    /// answer for a derived size while the image is still being prepared.
    pub async fn read(
        &self,
        reference: &ImageReference,
        stored: Stored,
    ) -> io::Result<Option<Vec<u8>>> {
        match tokio::fs::read(self.path(reference, stored)).await {
            Ok(bytes) => Ok(Some(bytes)),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(error),
        }
    }

    /// Every file of one image, source included. Absent is success: the caller
    /// is removing something, and it is gone either way.
    pub async fn remove(&self, reference: &ImageReference) -> io::Result<()> {
        match tokio::fs::remove_dir_all(self.directory(reference)).await {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error),
        }
    }

    /// Where this storage writes. For the operator's startup line, and for
    /// tests that look at the disk rather than through the API.
    pub fn root(&self) -> &Path {
        &self.root
    }
}

/// A short, opaque marker of what a file holds, for the `ETag` header.
///
/// A derived file never changes — a new upload is a new reference — so this
/// exists for the one case that does: the source served in place of a size
/// that is not ready yet.
pub fn entity_tag(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};

    let digest = Sha256::digest(bytes);
    format!("\"{}\"", URL_SAFE_NO_PAD.encode(&digest[..12]))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_generated_reference_survives_a_round_trip() {
        let reference = ImageReference::generate();

        assert_eq!(
            ImageReference::parse(reference.as_str()).as_ref(),
            Some(&reference),
        );
    }

    #[test]
    fn two_generated_references_differ() {
        assert_ne!(ImageReference::generate(), ImageReference::generate());
    }

    #[test]
    fn a_reference_that_walks_out_of_the_volume_is_refused() {
        for attempt in [
            "..",
            "../../etc/passwd",
            "..%2f..%2fetc%2fpasswd",
            "/etc/passwd",
            "0123456789abcdef0123456789abcde/",
            "0123456789abcdef0123456789abc..f",
            // The right shape, the wrong alphabet: uppercase and non-hex
            // letters are as refused as a slash.
            "0123456789ABCDEF0123456789abcdef",
            "0123456789abcdefzzzzzzzzzzzzzzzz",
            // The right alphabet, the wrong length.
            "0123456789abcdef",
            "0123456789abcdef0123456789abcdef0",
            "",
        ] {
            assert_eq!(ImageReference::parse(attempt), None, "accepted {attempt:?}");
        }
    }

    #[test]
    fn a_stored_file_is_named_after_its_size_and_format() {
        assert_eq!(Stored::Source.file_name(), "source.jpg");
        assert_eq!(
            Stored::Derived(Size::Thumbnail, Format::Avif).file_name(),
            "200.avif",
        );
        assert_eq!(
            Stored::Derived(Size::Large, Format::Jpeg).file_name(),
            "1400.jpg",
        );
    }

    #[test]
    fn a_path_stays_under_the_root() {
        let storage = Storage::at("/srv/media");
        let reference = ImageReference::parse("0123456789abcdef0123456789abcdef")
            .expect("a well-formed reference");

        assert_eq!(
            storage.path(&reference, Stored::Derived(Size::Medium, Format::Avif)),
            PathBuf::from("/srv/media/images/0123456789abcdef0123456789abcdef/600.avif"),
        );
    }
}
