-- The photographs a product is shown with, and where their files are.
--
-- The files themselves live on a mounted volume; this table is what says they
-- exist, in which order they are shown, and whether the sizes the shop serves
-- have been derived yet (docs/design/catalog.md § 5,
-- docs/backend/adr/0008-image-pipeline.md).

create table product_images (
    id               bigint      generated always as identity primary key,
    product_id       bigint      not null references products (id) on delete cascade,
    -- The single part of a file's path that varies, generated by the shop.
    -- Nothing a client sends ever reaches the filesystem: a file name from
    -- outside is a path traversal waiting to be written.
    reference        text        not null,
    -- Ascending, first shown first. Not unique per product on purpose:
    -- reordering rewrites several rows in one statement, and a unique index
    -- would refuse the intermediate state rather than the final one.
    position         integer     not null,
    -- Prompted at upload and not required: an image without it is flagged in
    -- the back office, which is more useful than an upload refused for a
    -- sentence the merchant will write in a moment
    -- (docs/design/catalog.md § 5).
    alternative_text text,
    -- Derivation runs after the upload has answered, so an image is readable
    -- before its sizes exist. Until then the shop serves the source.
    state            text        not null check (state in ('pending', 'ready', 'failed')),
    -- Of the source that was kept, so the interface can show a shape before a
    -- single derived file exists.
    source_width     integer     not null check (source_width > 0),
    source_height    integer     not null check (source_height > 0),
    -- Why the derivation failed, for the interface to show. Null otherwise.
    failure          text,
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

create unique index product_images_reference on product_images (reference);

-- The order a product's images are shown in, and the only order the back
-- office and the storefront read them in.
create index product_images_ordering on product_images (product_id, position, id);

-- What the deriver looks for when it starts and after every upload. Partial,
-- because a shop that has been running for a year has no pending images and
-- this index stays empty.
create index product_images_pending on product_images (created_at, id) where state = 'pending';

create trigger product_images_set_updated_at
    before update on product_images
    for each row execute function set_updated_at();
